version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GitHub_0104Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: CurrentDatePackage
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.serengeti_github_0104.integrations:gcd_awstg
  packages:
  - name: Serengeti_GitHub_0104Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
